/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List agents */
        get: operations["listAgents"];
        put?: never;
        /** Create an agent */
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        /** Get an agent */
        get: operations["getAgent"];
        /** Update an agent (partial) */
        put: operations["updateAgent"];
        post?: never;
        /** Delete an agent */
        delete: operations["deleteAgent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the AgentDef JSON Schema */
        get: operations["getAgentSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send an Anthropic-compatible message
         * @description Route to a Nova OS agent via `metadata.agent_id`; omit for the default agent.
         *
         *     When `stream:false`, returns a single `MessageResponse`.
         *     When `stream:true`, returns SSE with one `event:` line + JSON
         *     payload per event. Event types defined by `StreamEvent`.
         */
        post: operations["createMessage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/agents/messages/{message_id}/custom_tool_results": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a custom_tool_use result (Mode A inline)
         * @description Used when partner consumes the SSE stream directly. POST the result
         *     for an emitted `custom_tool_use` event; Nova OS resumes the agent
         *     loop and continues streaming on the original request connection.
         */
        post: operations["submitCustomToolResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List employees */
        get: operations["listEmployees"];
        put?: never;
        /** Create an employee */
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/employees/{employee_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        /** Get an employee */
        get: operations["getEmployee"];
        /** Update an employee (partial) */
        put: operations["updateEmployee"];
        post?: never;
        /** Delete an employee */
        delete: operations["deleteEmployee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/employees/{employee_id}/bundle/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        /** Download a portable .nova-bundle.zip */
        get: operations["exportEmployeeBundle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/employees/bundle/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import a .nova-bundle.zip */
        post: operations["importEmployeeBundle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/agents/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List jobs */
        get: operations["listJobs"];
        put?: never;
        /** Submit an async agent run */
        post: operations["createJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/agents/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        /** Get a job */
        get: operations["getJob"];
        put?: never;
        post?: never;
        /** Cancel a job (graceful drain) */
        delete: operations["cancelJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/agents/jobs/{job_id}/stream": {
        parameters: {
            query?: never;
            header?: {
                /** @description Resume from event seq — replays missed events from PG before live broadcast. */
                "Last-Event-ID"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        /** SSE stream for an async job (with replay) */
        get: operations["streamJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List documents in a collection */
        get: operations["listDocuments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/documents/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a document */
        post: operations["uploadDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a document */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/knowledge/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hybrid search across the knowledge base */
        post: operations["searchKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/knowledge/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest a document into a knowledge collection */
        post: operations["ingestKnowledge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/knowledge/collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every knowledge collection */
        get: operations["listKnowledgeCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/hooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List lifecycle-hook subscriptions */
        get: operations["listHooks"];
        put?: never;
        /**
         * Register a lifecycle-hook subscription
         * @description Note: as of v0.1.5 the in-memory store accepts subscriptions but
         *     the runtime hook bus does not yet bridge to it. Persistence and
         *     bus bridge land in a follow-up; partners wiring integrations now
         *     get a stable contract.
         */
        post: operations["createHook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/hooks/{hook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hook_id: string;
            };
            cookie?: never;
        };
        /** Get a hook subscription */
        get: operations["getHook"];
        put?: never;
        post?: never;
        /**
         * Deregister a hook subscription
         * @description Idempotent — returns 204 even if the subscription doesn't exist.
         */
        delete: operations["deleteHook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/filesystem/{tenant_id}/{session_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        /** List files in a workspace */
        get: operations["listFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/filesystem/{tenant_id}/{session_id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                session_id: string;
                /** @description File path within the workspace. URL-encoded; mount prefix is implicit. */
                path: string;
            };
            cookie?: never;
        };
        /** Read a file's raw bytes */
        get: operations["readFile"];
        /** Write or overwrite a file */
        put: operations["writeFile"];
        post?: never;
        /**
         * Delete a file
         * @description Idempotent — returns 204 even if the file doesn't exist.
         */
        delete: operations["deleteFile"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List users */
        get: operations["listUsers"];
        put?: never;
        /** Create a user (default password; trigger reset on first sign-in) */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        /** Get a user */
        get: operations["getUser"];
        put?: never;
        post?: never;
        /** Delete a user */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read every platform setting */
        get: operations["listSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        /** Read a single setting */
        get: operations["getSetting"];
        /** Write a single setting */
        put: operations["putSetting"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Nova OS native session
         * @description Native partner-prefix session create. Shares the SessionStore
         *     with the Anthropic-compat /v1/sessions surface — state is
         *     consistent across the two mounts. No `anthropic-beta` header
         *     gate; partner-friendly response shape.
         */
        post: operations["createManagedSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        /** Get a session by ID */
        get: operations["getManagedSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/v1/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Boot-time persona manifest with ETag round-trip
         * @description Returns the manifest envelope (`manifest_version` sha256 + every
         *     registered persona). Partners cache by `manifest_version` and
         *     send `If-None-Match` on subsequent fetches; the server replies
         *     304 with no body when the manifest hasn't changed.
         */
        get: operations["listPersonas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/v1/personas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Fetch a single persona by id
         * @description Returns the manifest entry for a single registered persona. 404 with
         *     a PersonaNotFoundError envelope when no persona matches the id.
         */
        get: operations["getPersonaByID"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/managed/deployment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read this instance's capabilities, model tiers, locales, and auth contract
         * @description Minimal capabilities read for boot-time client configuration. Lets a
         *     web or iOS client discover server version, optional feature labels,
         *     resolved model tiers, enabled locales, and the OIDC auth contract
         *     without probing individual endpoints. Per the contract-unification
         *     design (D1, lean: derive), this is deliberately small and advisory —
         *     `GET /agents/v1/personas` remains the source of truth for which agents
         *     exist.
         */
        get: operations["getDeployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @enum {string} */
            type: "invalid_request_error" | "authentication_error" | "permission_error" | "not_found_error" | "rate_limit_error" | "billing_error" | "upstream_error" | "vertex_schema_error" | "validation_error" | "internal_error";
            message: string;
            /** @description When applicable, the request parameter that failed validation. */
            param?: string;
            /** @description Machine-readable subcode (e.g., "credits_exhausted", "USAGE_LIMIT_EXCEEDED"). */
            code?: string;
            /** @description Seconds — present on rate_limit_error. */
            retry_after?: number;
            /** @description Present on vertex_schema_error — the tool whose schema is invalid. */
            tool_name?: string;
            /** @description Present on vertex_schema_error — JSON path to the offending parameter. */
            parameter_path?: string;
            /** @description Human-readable hint for actionable errors. */
            fix_hint?: string;
        };
        /**
         * @description Whether this agent dispatches to other skill agents (persona) or
         *     executes one skill directly (skill). Maps to nova-os internals;
         *     partners only see the discriminator.
         * @enum {string}
         */
        AgentType: "persona" | "skill";
        ModelSlot: {
            /** @description Model identifier in `<vendor>/<model>` shape (e.g., `gemini/gemini-3.1-pro-preview`). */
            primary: string;
            /**
             * @description Ordered fallback chain. Activates on rate-limit / 5xx / vendor outage /
             *     Vertex 400 schema-error before falling through to the next resolution level.
             */
            fallback?: string[];
        };
        /**
         * @description Three-slot model configuration. Any slot may be omitted; resolution
         *     falls through per the spec (per-call → per-skill → per-agent →
         *     per-employee → server default).
         */
        ModelConfig: {
            /** @description Main chat / synthesis model. */
            answer?: components["schemas"]["ModelSlot"];
            /** @description Brain / DAG planning model. */
            planner?: components["schemas"]["ModelSlot"];
            /** @description Cheap tier for skill agents + report sections. */
            skill?: components["schemas"]["ModelSlot"];
        };
        /**
         * @description Web search backend selection. `auto` uses the server's default
         *     priority order (operator-configured).
         * @enum {string}
         */
        WebSearchBackend: "tavily" | "brave" | "exa" | "searxng" | "meganova" | "auto";
        /**
         * @description Persona-level web-search configuration. Resolved per-invocation on
         *     ``skill_deep_research`` via ``searchctx.WebSearchConfigFromContext``.
         *     Field names changed in nova-os PR #212 (closes #200) — old
         *     ``backend`` / ``fallback`` are no longer accepted.
         */
        WebSearchConfig: {
            /**
             * @description Primary search backend. ``auto`` falls through to the server's
             *     ``DefaultSearcher()`` priority order.
             * @default auto
             */
            primary_backend: components["schemas"]["WebSearchBackend"];
            /**
             * @description Ordered fallback chain. Used on empty/error/off-topic results.
             *     Wraps the primary in a ``FallbackSearcher`` whose ``Name()``
             *     renders as ``primary→fallback1→fallback2``.
             */
            fallback_chain?: components["schemas"]["WebSearchBackend"][];
            /**
             * @description Wrap the search call with the LLM reformulator. Improves
             *     retrieval quality on broad queries. Applied only to keyword
             *     backends; bundled-extraction backends handle reformulation
             *     internally.
             * @default true
             */
            reformulator: boolean;
            /** @description Custom recency markers for the recency-intent escalator. */
            recency_terms?: string[];
        };
        /**
         * @description A subset of JSON Schema Draft 2020-12 used for tool input schemas.
         *     Vertex AI rejects `type:array` without `items` — the SDK validator
         *     enforces `items` is present everywhere on write.
         */
        JSONSchemaObject: {
            [key: string]: unknown;
        };
        CustomToolCallback: {
            /**
             * Format: uri
             * @description HTTPS URL (or http://localhost:* for dev). Webhook target.
             */
            url: string;
            auth: {
                /** @enum {string} */
                type: "hmac_sha256";
                /** @description Settings-store key holding the HMAC shared secret. */
                secret_ref: string;
            };
            /** @default 30 */
            timeout_sec: number;
            retry?: {
                /** @default 3 */
                max_attempts: number;
                /**
                 * @default exponential
                 * @enum {string}
                 */
                backoff: "exponential" | "linear" | "fixed";
            };
        };
        CustomTool: {
            /** @description Lowercase snake_case identifier; unique within the agent. */
            name: string;
            /** @description Free-text description shown to the LLM via the tool definition. */
            description?: string;
            input_schema: components["schemas"]["JSONSchemaObject"];
            /**
             * @description Per-tool callback override. Falls through to agent.callback then
             *     employee.callback. Required at one of the three levels.
             */
            callback?: components["schemas"]["CustomToolCallback"];
        };
        Skill: {
            name: string;
            /** @description Per-skill model override (highest priority below per-call). */
            model?: string;
        };
        Agent: {
            /** @description Slug generated from the agent name. */
            id: string;
            readonly version?: number;
            name: string;
            /** @description Optional model override; empty means inherit the server tier default. */
            model?: string;
            system?: string;
            tools?: string[];
            /** @description Owner email; defaults to the caller when omitted. */
            owner?: string;
            /** @enum {string} */
            visibility?: "" | "private" | "public";
            agent_type?: components["schemas"]["AgentType"];
            brain?: boolean;
            capabilities?: string[];
            max_turns?: number;
            output_type?: components["schemas"]["OutputTypeContract"];
            knowledge_bindings?: string[];
            guardrails?: {
                [key: string]: unknown;
            };
            filesystem?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            readonly created_at?: string;
            /** @deprecated */
            type?: components["schemas"]["AgentType"];
            /** @deprecated */
            owner_employee?: string;
            /** @deprecated */
            system_prompt?: string;
        };
        AgentCreate: {
            name: string;
            model?: string;
            system?: string;
            tools?: string[];
            owner?: string;
            /** @enum {string} */
            visibility?: "" | "private" | "public";
            filesystem?: {
                [key: string]: unknown;
            };
            agent_type?: components["schemas"]["AgentType"];
            brain?: boolean;
            capabilities?: string[];
            max_turns?: number;
            output_type?: components["schemas"]["OutputTypeContract"];
            knowledge_bindings?: string[];
            guardrails?: {
                [key: string]: unknown;
            };
        };
        /** @description Partial update; only the fields supplied are changed. */
        AgentUpdate: {
            name?: string;
            model?: string;
            system?: string;
            tools?: string[];
            owner?: string;
            /** @enum {string} */
            visibility?: "" | "private" | "public";
            filesystem?: {
                [key: string]: unknown;
            };
            agent_type?: components["schemas"]["AgentType"];
            brain?: boolean;
            capabilities?: string[];
            max_turns?: number;
            output_type?: components["schemas"]["OutputTypeContract"];
            knowledge_bindings?: string[];
            guardrails?: {
                [key: string]: unknown;
            };
        };
        AgentList: {
            data: components["schemas"]["Agent"][];
            has_more?: boolean;
            next_cursor?: string;
        };
        Employee: {
            id: string;
            display_name?: string;
            description?: string;
            /** @description Cascades to all owned agents unless they override. */
            model_config?: components["schemas"]["ModelConfig"];
            /** @description Cascades to owned agents. */
            web_search_config?: components["schemas"]["WebSearchConfig"];
            /** @description Catch-all callback for any owned-agent tool with no closer match. */
            callback?: components["schemas"]["CustomToolCallback"];
            /** @description IDs of agents owned by this employee. */
            readonly agents?: string[];
            /** @description Filesystem path under users/<owner>/employees/<id>/. */
            readonly storage_path?: string;
            /** Format: date-time */
            readonly created_at?: string;
            /** Format: date-time */
            readonly updated_at?: string;
        };
        EmployeeCreate: WithRequired<components["schemas"]["Employee"], "id">;
        EmployeeUpdate: {
            display_name?: string;
            description?: string;
            model_config?: components["schemas"]["ModelConfig"];
            web_search_config?: components["schemas"]["WebSearchConfig"];
            callback?: components["schemas"]["CustomToolCallback"];
        };
        EmployeeList: {
            data: components["schemas"]["Employee"][];
            has_more?: boolean;
            next_cursor?: string;
        };
        BundleManifest: {
            /** @enum {integer} */
            schema_version: 1;
            employee_id: string;
            nova_os_min_version: string;
            /** Format: date-time */
            created_at: string;
            agents?: string[];
            knowledge_files?: number;
        };
        BundleImportResult: {
            employee_id: string;
            agents_imported: number;
            knowledge_files_indexed?: number;
            warnings?: string[];
        };
        /** @enum {string} */
        Role: "user" | "assistant" | "system";
        TextBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TextBlock";
            text: string;
        };
        ToolUseBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ToolUseBlock";
            id: string;
            name: string;
            input: {
                [key: string]: unknown;
            };
        };
        ToolResultBlock: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ToolResultBlock";
            tool_use_id: string;
            content: string | components["schemas"]["TextBlock"][];
            /** @default false */
            is_error: boolean;
        };
        ContentBlock: components["schemas"]["TextBlock"] | components["schemas"]["ToolUseBlock"] | components["schemas"]["ToolResultBlock"];
        Message: {
            role: components["schemas"]["Role"];
            content: string | components["schemas"]["ContentBlock"][];
        };
        ToolDefinition: {
            name: string;
            description?: string;
            input_schema: components["schemas"]["JSONSchemaObject"];
            /**
             * @default custom
             * @enum {string}
             */
            type: "custom" | "web_search_20250305" | "text_editor_20250124" | "bash_20250124";
        };
        MessageRequest: {
            messages: components["schemas"]["Message"][];
            /** @description Per-call override; matches Anthropic shape, also accepts <vendor>/<model>. */
            model?: string;
            /** @default 4096 */
            max_tokens: number;
            temperature?: number;
            system?: string;
            tools?: components["schemas"]["ToolDefinition"][];
            /** @default false */
            stream: boolean;
            metadata?: {
                /**
                 * @description Target a specific Nova OS agent/persona for this turn; omit
                 *     for the default agent. Typed here so generated clients can set
                 *     it without falling back to untyped additionalProperties.
                 */
                agent_id?: string;
                /** @description Per-call planner toggle (3-state — null inherits server default). */
                brain?: boolean;
                /** @description Per-call orchestration event streaming toggle. */
                stream_events?: boolean;
                /** @description Per-call planner-thinking event toggle. */
                stream_thinking?: boolean;
            } & {
                [key: string]: unknown;
            };
        };
        MessageResponse: {
            id: string;
            /** @enum {string} */
            type?: "message";
            role: components["schemas"]["Role"];
            content: components["schemas"]["ContentBlock"][];
            /** @description Resolved model that handled the request. */
            model: string;
            /** @enum {string} */
            stop_reason: "end_turn" | "max_tokens" | "stop_sequence" | "tool_use";
            usage?: {
                input_tokens?: number;
                output_tokens?: number;
            };
            /** @description Nova OS extension — same as `model`, surfaced for clarity. */
            model_used?: string;
            /** @description Nova OS extension — true if a fallback model handled the request. */
            fallback_triggered?: boolean;
            /**
             * @description Nova OS extension — populated only when the agent declared an
             *     `output_type` contract AND the reply failed validation AND the
             *     agent's `violation_mode` is `log` or `repair` (with `error`,
             *     the response is a 422 instead). Empty array means no violations.
             */
            output_violations?: components["schemas"]["OutputViolation"][];
            /**
             * @description Nova OS extension (v0.1.5+) — Brain's dispatch hint to the
             *     partner UI. Always present on terminal replies; partners that
             *     don't consume route hints can ignore the field. Three kinds:
             *     `render_inline`, `navigate_to`, `ask_clarification`.
             */
            route_hint?: components["schemas"]["RouteHint"];
        };
        StreamEventTextDelta: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventTextDelta";
            content: string;
        };
        StreamEventToolUse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventToolUse";
            id: string;
            name: string;
            input: {
                [key: string]: unknown;
            };
        };
        StreamEventToolResult: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventToolResult";
            tool_use_id: string;
            /** @description Preview-truncated (~1KB on the wire); full payload in call_log. */
            output_summary?: string;
            is_error?: boolean;
        };
        StreamEventCustomToolUse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventCustomToolUse";
            id: string;
            name: string;
            input: {
                [key: string]: unknown;
            };
        };
        StreamEventThinking: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventThinking";
            content: string;
        };
        StreamEventError: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventError";
            error: components["schemas"]["Error"];
        };
        StreamEventDone: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventDone";
            /** @enum {string} */
            status: "completed" | "failed" | "cancelled";
            message_id?: string;
        };
        /**
         * @description Nova OS extension (v0.1.5+) — emitted exactly once per terminal
         *     message right before `done`. Carries Brain's dispatch decision so
         *     partner UIs can react before the full reply is rendered.
         */
        StreamEventRouteHint: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "StreamEventRouteHint";
            route_hint: components["schemas"]["RouteHint"];
        };
        StreamEvent: components["schemas"]["StreamEventTextDelta"] | components["schemas"]["StreamEventToolUse"] | components["schemas"]["StreamEventToolResult"] | components["schemas"]["StreamEventCustomToolUse"] | components["schemas"]["StreamEventThinking"] | components["schemas"]["StreamEventError"] | components["schemas"]["StreamEventDone"] | components["schemas"]["StreamEventRouteHint"];
        /**
         * @description Structured-output contract for agent replies. When set, Nova OS
         *     validates every assistant reply against `schema` before return.
         *     Server-side since v0.1.4.
         */
        OutputTypeContract: {
            /** @description JSON Schema 2020-12 the assistant reply must validate against. */
            schema: components["schemas"]["JSONSchemaObject"];
            /**
             * @description How to handle a reply that fails validation:
             *     - `error` — return HTTP 422 with the violations.
             *     - `log` — return the reply as-is plus `output_violations`; partner decides what to do.
             *     - `repair` — re-prompt the model once with the schema in the system prompt;
             *       return whichever attempt validates, plus `output_violations` from the first.
             * @default error
             * @enum {string}
             */
            violation_mode: "error" | "log" | "repair";
        };
        OutputViolation: {
            /** @description JSON Pointer into the assistant reply where the violation occurred. */
            path: string;
            /** @description Human-readable description of the failure (from the JSON Schema validator). */
            message: string;
            /** @description The JSON Schema keyword that failed (e.g. `type`, `required`, `enum`). */
            keyword?: string;
        };
        /**
         * @description Brain decided the reply is the answer — render it inline in the
         *     partner's chat UI. No navigation needed.
         */
        RouteHintRenderInline: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "RouteHintRenderInline";
        };
        /**
         * @description Brain decided the partner UI should navigate to a route. The
         *     template name MUST match a key in the agent's `route_templates`;
         *     the server interpolates `params` into the URL template.
         */
        RouteHintNavigateTo: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "RouteHintNavigateTo";
            /** @description Key into the agent's `route_templates` map. */
            template: string;
            /** @description Values to interpolate into the template's `{placeholder}` segments. */
            params?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description Brain decided more input is needed before answering — partner UI
         *     should present a clarification prompt rather than rendering the
         *     reply as final.
         */
        RouteHintAskClarification: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "RouteHintAskClarification";
            /** @description Short human-readable rationale (e.g. `missing_jurisdiction`). */
            reason: string;
        };
        /**
         * @description Brain's dispatch hint, present on every terminal reply (v0.1.5+).
         *     Three kinds — partners switch on `kind` to decide UI behaviour.
         */
        RouteHint: components["schemas"]["RouteHintRenderInline"] | components["schemas"]["RouteHintNavigateTo"] | components["schemas"]["RouteHintAskClarification"];
        CustomToolResultRequest: {
            tool_use_id: string;
            output: string;
            /** @default false */
            is_error: boolean;
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        Job: {
            job_id: string;
            agent_id: string;
            employee_id?: string;
            status: components["schemas"]["JobStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at?: string;
            /** Format: date-time */
            finished_at?: string;
            result?: components["schemas"]["MessageResponse"];
            error?: components["schemas"]["Error"];
            readonly event_count?: number;
            readonly instance_id?: string;
        };
        JobCreate: {
            agent_id: string;
            messages: components["schemas"]["Message"][];
            model?: string;
            tools?: components["schemas"]["ToolDefinition"][];
            metadata?: {
                [key: string]: unknown;
            };
        };
        JobList: {
            data: components["schemas"]["Job"][];
            has_more?: boolean;
            next_cursor?: string;
        };
        Document: {
            readonly id: string;
            /** @description File name or extracted title */
            title: string;
            /** @description Collection path (e.g. "contracts/2026") */
            path?: string;
            /** @description Document type — pdf, docx, md, etc. */
            type?: string;
            /** Format: int64 */
            readonly size_bytes?: number;
            /** @description Parent collection (empty = root) */
            collection_id?: string;
            /** @description Mime, pages, author, etc. */
            metadata?: {
                [key: string]: string;
            };
            /** Format: date-time */
            readonly created_at?: string;
        };
        DocumentList: {
            data: components["schemas"]["Document"][];
            has_more?: boolean;
            next_cursor?: string;
        };
        KnowledgeChunk: {
            content: string;
            collection?: string;
            document_id?: string;
            /** Format: float */
            score?: number;
            metadata?: {
                [key: string]: unknown;
            };
        };
        KnowledgeSearchRequest: {
            query: string;
            /** @description Collection to search; empty = caller's own collection. */
            collection?: string;
            /** @default 5 */
            top_k: number;
            /** Format: float */
            threshold?: number;
        };
        KnowledgeSearchResponse: {
            data: components["schemas"]["KnowledgeChunk"][];
        };
        KnowledgeIngestRequest: {
            title?: string;
            /** @description Document text (already extracted) */
            content: string;
            /**
             * @description Target collection; defaults to "default".
             * @default default
             */
            collection: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        KnowledgeCollectionList: {
            data: string[];
        };
        /**
         * @description The 9 canonical lifecycle events. Validated server-side at
         *     registration time; unknown values return 400.
         * @enum {string}
         */
        HookEvent: "SessionStart" | "SessionEnd" | "UserPromptSubmit" | "PreToolUse" | "PostToolUse" | "PreInference" | "PostInference" | "Stop" | "Error";
        HookSubscription: {
            readonly id: string;
            event: components["schemas"]["HookEvent"];
            /** Format: uri */
            target_url: string;
            /** @description Env var name holding the HMAC shared secret on the partner side. */
            secret_env?: string;
            description?: string;
            /** @default true */
            enabled: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        HookSubscriptionCreate: {
            event: components["schemas"]["HookEvent"];
            /** Format: uri */
            target_url: string;
            secret_env?: string;
            description?: string;
            enabled?: boolean;
        };
        HookSubscriptionList: {
            data: components["schemas"]["HookSubscription"][];
        };
        FileMeta: {
            /** @description Agent-visible path including mount prefix (e.g. "/workspace/PLAN.md"). */
            path: string;
            /**
             * Format: int64
             * @description Plaintext byte length.
             */
            size: number;
            /** Format: date-time */
            mtime: string;
            content_type?: string;
            /** @description Hex-encoded SHA-256 of the plaintext. Used for If-Match optimistic concurrency. */
            sha256?: string;
        };
        FileMetaList: {
            data: components["schemas"]["FileMeta"][];
            /** @description True when truncated by the limit query param. */
            has_more?: boolean;
        };
        User: {
            readonly id: string;
            /** Format: email */
            email: string;
            name?: string;
            /** @enum {string} */
            role: "admin" | "manager" | "developer" | "employee";
            readonly must_change_password?: boolean;
            /** Format: date-time */
            readonly created_at?: string;
        };
        UserCreate: {
            /** Format: email */
            email: string;
            name?: string;
            /**
             * @default employee
             * @enum {string}
             */
            role: "admin" | "manager" | "developer" | "employee";
        };
        UserList: {
            data: components["schemas"]["User"][];
        };
        SettingValue: {
            key: string;
            /** @description Setting value — type varies per key (string for model identifiers, int for thresholds, bool for feature flags). */
            value: unknown;
        };
        /**
         * @description Resolved persona triage default. ``always_brain`` forces the
         *     planner; ``never_brain`` skips it; ``conditional`` defers to
         *     the per-turn regex/LLM triage chain. Per-call ``metadata.brain``
         *     on the messages endpoint still wins as an override. Resolved
         *     server-side by the canonical ``persona.ResolveTriage`` function
         *     — partners receive the projected value, not the raw frontmatter.
         * @enum {string}
         */
        PersonaTriage: "always_brain" | "never_brain" | "conditional";
        PersonaManifestEntry: {
            id: string;
            display_name: string;
            /** @description Skill labels the persona dispatches to. */
            capabilities: string[];
            triage: components["schemas"]["PersonaTriage"];
            /** @description Which RouteHint kinds the persona emits at all (drives partner UI prep). */
            emits_route_hint_kinds: ("render_inline" | "navigate_to" | "ask_clarification")[];
            /** @description Keys into the agent's route_templates map; partners pre-resolve URL templates. */
            route_template_names: string[];
        };
        /**
         * @description Boot-time persona discovery contract. Partners cache by
         *     ``manifest_version`` (sha256 over canonical-JSON) and use
         *     ``If-None-Match`` on subsequent fetches to short-circuit at 304.
         */
        Manifest: {
            /**
             * @description ``sha256:<hex>`` — emitted as ``ETag``. Partners send
             *     ``If-None-Match: <manifest_version>`` to skip the body when
             *     unchanged.
             */
            manifest_version: string;
            personas: components["schemas"]["PersonaManifestEntry"][];
        };
        /** @description Returned on GET /agents/v1/personas/{id} miss. Distinct envelope from the standard Error type for backwards-compat with the existing `/agents/v1/*` surface. */
        PersonaNotFoundError: {
            /** @example persona not found */
            error: string;
            /** @description The requested persona id (echoed back). */
            id: string;
        };
        Session: {
            /** @description Format: sess_<uuid>. */
            readonly id: string;
            agent_id: string;
            environment_id?: string;
            /** @description Session-default LLM override; per-event model on the messages endpoint takes precedence. */
            model?: string;
            /** Format: date-time */
            readonly created_at?: string;
        };
        SessionCreate: {
            agent_id: string;
            environment_id?: string;
            model?: string;
        };
        /**
         * @description Minimal, derive-friendly capabilities read so a client (web/iOS) can
         *     discover what this Nova OS instance supports without probing each
         *     endpoint. Per the contract-unification design (D1, lean: derive),
         *     this is intentionally small — the persona manifest
         *     (`GET /agents/v1/personas`) remains the source of truth for *which*
         *     agents exist; this read surfaces server-level feature flags, model
         *     tiers, enabled locales, and the auth contract clients need at boot.
         *     All fields are advisory; absence means "not advertised", not "off".
         */
        Deployment: {
            /** @description Nova OS server version (e.g. "v0.1.9"). "dev"/"unknown" on unstamped builds. */
            version: string;
            /**
             * @description Stable string labels for optional server features a client may
             *     branch on (e.g. "observational_memory", "report_generator",
             *     "async_jobs", "workflows", "knowledge_gate", "ag_ui_streaming").
             *     Open-ended — unknown labels are ignored by older clients.
             */
            capabilities: string[];
            /**
             * @description Resolved model tiers (advisory; no secrets). Lets a client show
             *     "powered by" / pick a tier without hardcoding model ids.
             */
            models?: {
                /** @description Default answer/synthesis model id. */
                answer?: string;
                /** @description Cheap-tier skill/section model id. */
                skill?: string;
                /** @description Planner/brain model id. */
                brain?: string;
            };
            /** @description Enabled UI locales; first is the default (e.g. ["en","zh-CN"]). */
            locales?: string[];
            /**
             * @description The interactive-login contract clients should use. OIDC details
             *     live in the hand-authored `docs/oidc-client-flow.md`; this block
             *     only advertises the issuer + whether OIDC is enabled so a client
             *     can construct the Auth-Code+PKCE flow.
             */
            auth?: {
                /** @description True when the embedded OIDC provider is available for interactive login. */
                oidc_enabled?: boolean;
                /** @description OIDC issuer / public base URL (discovery root). Empty when OIDC disabled. */
                issuer?: string;
            };
        };
    };
    responses: {
        /** @description Request validation failed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid bearer token. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Token valid but lacks permission for this operation. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found (or hidden from this token's scope). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Too many requests. */
        RateLimited: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description SDK or OpenAPI hash major mismatch. */
        UpgradeRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listAgents: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
                /** @description Filter to agents owned by this email. */
                owner?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Agent created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentUpdate"];
            };
        };
        responses: {
            /** @description Updated agent. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getAgentSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AgentDef JSON Schema. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            426: components["responses"]["UpgradeRequired"];
        };
    };
    createMessage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Message response (non-stream) or SSE stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            426: components["responses"]["UpgradeRequired"];
            429: components["responses"]["RateLimited"];
        };
    };
    submitCustomToolResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                message_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomToolResultRequest"];
            };
        };
        responses: {
            /** @description Result accepted; streaming resumes on the original connection. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listEmployees: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeCreate"];
            };
        };
        responses: {
            /** @description Employee created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmployeeUpdate"];
            };
        };
        responses: {
            /** @description Updated employee. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Employee"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    exportEmployeeBundle: {
        parameters: {
            query?: {
                include_knowledge?: boolean;
            };
            header?: never;
            path: {
                employee_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Zip bundle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    importEmployeeBundle: {
        parameters: {
            query?: {
                on_conflict?: "overwrite" | "skip" | "error";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/zip": string;
            };
        };
        responses: {
            /** @description Imported. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BundleImportResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Conflict — existing employee with same id and `on_conflict=error`. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: components["schemas"]["JobStatus"];
                agent_id?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Job queued. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    cancelJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamJob: {
        parameters: {
            query?: never;
            header?: {
                /** @description Resume from event seq — replays missed events from PG before live broadcast. */
                "Last-Event-ID"?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["StreamEvent"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /** @description Collection to enumerate; empty = root. */
                collection_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Document list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    uploadDocument: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    /** @description Target collection; empty = root. */
                    collection_id?: string;
                };
            };
        };
        responses: {
            /** @description Document uploaded and auto-indexed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Document"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    searchKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeSearchRequest"];
            };
        };
        responses: {
            /** @description Ranked passages. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeSearchResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    ingestKnowledge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeIngestRequest"];
            };
        };
        responses: {
            /** @description Document ingested. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status?: "ingested";
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listKnowledgeCollections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection name list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeCollectionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listHooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HookSubscriptionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createHook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HookSubscriptionCreate"];
            };
        };
        responses: {
            /** @description Subscription created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HookSubscription"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getHook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HookSubscription"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteHook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listFiles: {
        parameters: {
            query?: {
                mount?: string;
                /** @description filepath.Match pattern applied to the basename. */
                glob?: string;
                recursive?: "1" | "true";
                limit?: number;
            };
            header?: never;
            path: {
                tenant_id: string;
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File list with metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMetaList"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    readFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                session_id: string;
                /** @description File path within the workspace. URL-encoded; mount prefix is implicit. */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File content (Content-Type from the file's stored metadata). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    writeFile: {
        parameters: {
            query?: never;
            header?: {
                /** @description SHA-256 of the current content for optimistic concurrency. */
                "If-Match"?: string;
            };
            path: {
                tenant_id: string;
                session_id: string;
                /** @description File path within the workspace. URL-encoded; mount prefix is implicit. */
                path: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description File written. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileMeta"];
                };
            };
            403: components["responses"]["Forbidden"];
            /** @description If-Match precondition failed. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Quota exceeded. */
            507: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteFile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
                session_id: string;
                /** @description File path within the workspace. URL-encoded; mount prefix is implicit. */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Map of key → value. Value type varies per key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Setting value. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingValue"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    putSetting: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description New value (type varies per key). */
                    value: unknown;
                };
            };
        };
        responses: {
            /** @description Updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingValue"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createManagedSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Session created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getManagedSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listPersonas: {
        parameters: {
            query?: never;
            header?: {
                /** @description Cached `manifest_version` from a prior fetch. */
                "If-None-Match"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full manifest. */
            200: {
                headers: {
                    /** @description The current `manifest_version`. Round-trip via `If-None-Match`. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Manifest"];
                };
            };
            /** @description Manifest unchanged. No body. Partner's cached version is current. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPersonaByID: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persona entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaManifestEntry"];
                };
            };
            /** @description No persona with that id is registered. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaNotFoundError"];
                };
            };
        };
    };
    getDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment capabilities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
